// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "&SQVQPOOO!QQPO'#C_O!VQPO'#CpO!^QPO'#CsO!eQPO'#C^O$^QPO'#CmOOQO'#Cy'#CyOOQO'#C^'#C^OOQO'#Cz'#CzQVQPOOO$eQPO,58yOOQO,59[,59[O$jQPO,59[OOQO,59_,59_O$qQPO,59_O%pQPO,59bO%wQPO'#CoOOQO'#Co'#CoOOQO'#C|'#C|O&rQPO,59XOOQO,59X,59XOOQO-E6x-E6xO'hQPO1G.eOOQO1G.v1G.vOOQO1G.y1G.yOOQO'#Cx'#CxOOQO'#C}'#C}O'oQPO1G.|OOQO1G.|1G.|OOQO-E6z-E6zOOQO1G.s1G.sOOQO'#Cc'#CcOOQO'#C{'#C{O'vQPO7+$POOQO7+$P7+$POOQO-E6{-E6{OOQO7+$h7+$hOOQO-E6y-E6yOOQO<<Gk<<Gk",
  stateData:
    "(Y~OtOS~OSPOTVOWVOXVOYSO[VO]VO^VO_VObTOeQOhROkUO~OTYO~OfZO~PVOi]O~PVOk_OSQXTQXWQXXQXYQX[QX]QX^QX_QXbQXeQXhQXrQXfQXiQX~OSPOTaOWaOXaOY`O[aO]aO^aO_aOeQOhRO~ObdO~P#iOUfO~OfgO~PVOihO~PVOSPOTiOWiOXiOYiO[iO]iO^iO_iObTOeQOhRO~OklO~P$xOk_OScXTcXWcXXcXYcX[cX]cX^cX_cXbcXecXhcX~ObnO~P#iOToOWoOXoOYoOZoO[oO]oO^oO_oO~O`rO~P&yOktO~P$xO`vO~P&yObkWXYT]t_Y~",
  goto: "#{rPPs{PPP!]PPPPPPPPP!aP!m{PP{PP!qP!}#R#Z#i#o#u]WOQRX[^[VOQRX[^SaTcTi_kTpfq[VOQRX[^Ti_kTbTc[VOQRX[^TaTcTj_k]VOQRX[^QXOQ[QQ^RVeX[^QqfRuqQcTRmcQk_Rsk",
  nodeNames:
    "⚠ Prompt Item ExtensionCall Dollar Identifier LParen ExtensionItem String Tag Number Equals Comma Escaped Pipe Text RParen Randomizer DoublePipe RandomizerContent Strengthening LBrace RBrace Weakening LBracket RBracket NumericEmphasis DoubleColon NumericContent CloseAll",
  maxTerm: 36,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData:
    "6v~R!SOX$_XZ%iZ]&^]^%i^p$_pq%iqr$_rs(ost$_tu)vux$_xy){yz*Qz|$_|}*V}!O*[!O!Q$_!Q![/S![!]3m!]!_$_!_!`3z!`!b$_!c!}4P!}#O5f#O#P5k#P#Q6Y#Q#T$_#T#o4P#o#p6_#p#q6d#q#r6q#r#y$_#y#z&^#z$f$_$f$g&^$g#BY$_#BY#BZ&^#BZ$IS$_$IS$I_&^$I_$I|$_$I|$JO&^$JO$JT$_$JT$JU&^$JU$KV$_$KV$KW&^$KW&FU$_&FU&FV&^&FV;'S$_;'S;=`%c<%lO$_~$d__~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}![$_!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~%fP;=`<%l$_~%nYt~X^%ipq%i#y#z%i$f$g%i#BY#BZ%i$IS$I_%i$I|$JO%i$JT$JU%i$KV$KW%i&FU&FV%i~&ert~_~OX$_XZ%iZ]&^]^%i^p$_pq%iqr$_st$_ux$_z|$_}![$_!]!_$_!`!b$_!c!}$_#Q#o$_#r#y$_#y#z&^#z$f$_$f$g&^$g#BY$_#BY#BZ&^#BZ$IS$_$IS$I_&^$I_$I|$_$I|$JO&^$JO$JT$_$JT$JU&^$JU$KV$_$KV$KW&^$KW&FU$_&FU&FV&^&FV;'S$_;'S;=`%c<%lO$_~(rVOr(ors)Xs#O(o#O#P)^#P;'S(o;'S;=`)p<%lO(o~)^OW~~)aTOY(oZ](o^;'S(o;'S;=`)p<%lO(o~)sP;=`<%l(o~){OS~~*QOU~~*VO`~~*[O[~~*a`_~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!Q$_!Q![+c!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~+jbY~_~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O$_!O!P,r!P!Q$_!Q![+c!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~,w`_~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!Q$_!Q![-y!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~.Q`Y~_~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!Q$_!Q![-y!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~/ZeY~_~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O0l!O!P,r!P!Q$_!Q![2R!]!_$_!`!b$_!c!}0l#Q#R$_#R#S0l#S#T$_#T#o0l#r;'S$_;'S;=`%c<%lO$_~0sdX~_~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O0l!O!Q$_!Q![0l!]!_$_!`!b$_!c!}0l#Q#R$_#R#S0l#S#T$_#T#o0l#r;'S$_;'S;=`%c<%lO$_~2[eX~Y~_~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O0l!O!P,r!P!Q$_!Q![2R!]!_$_!`!b$_!c!}0l#Q#R$_#R#S0l#S#T$_#T#o0l#r;'S$_;'S;=`%c<%lO$_~3rP_~![!]3u~3zOk~~4POZ~~4WdT~_~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O4P!O!Q$_!Q![4P!]!_$_!`!b$_!c!}4P#Q#R$_#R#S4P#S#T$_#T#o4P#r;'S$_;'S;=`%c<%lO$_~5kOh~~5nTOY5}Z]5}^;'S5};'S;=`6S<%lO5}~6SO]~~6VP;=`<%l5}~6_Oi~~6dOe~~6iP^~#p#q6l~6qOb~~6vOf~",
  tokenizers: [0],
  topRules: { Prompt: [0, 1] },
  tokenPrec: 321,
});
