// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "&fQVQPOOO#nQPO'#C^O#xQPO'#CwO$PQPO'#CxO$WQPO'#C^O%YQPO'#CuOOQO'#C{'#C{OOQO'#C^'#C^OOQO'#C|'#C|QVQPOOO%aQPO,58yOOQO,59c,59cO%fQPO,59cOOQO,59d,59dO%mQPO,59dO&{QPO,59eO'SQPO'#C_O'XQPO'#CvO(VQPO'#CyOOQO'#Cv'#CvOOQO'#DO'#DOO([QPO,59aOOQO,59a,59aOOQO-E6z-E6zO)jQPO1G.eOOQO1G.}1G.}OOQO1G/O1G/OO)qQPO'#CzOOQO'#Cz'#CzOOQO'#DP'#DPO*{QPO1G/POOQO1G/P1G/POOQO-E6|-E6|OOQO1G.{1G.{OOQO'#Cc'#CcOOQO'#C}'#C}O+SQPO7+$POOQO7+$P7+$POOQO-E6}-E6}OOQO7+$k7+$kOOQO-E6{-E6{OOQO<<Gk<<Gk",
  stateData:
    "+h~OvOS~OSPOTVOUVOWVOXVOYVOZSO[SO]VO^VO_VO`TOaUObQOdROfVOgVOhVO~OSQXUQXWQXXQXYQXZQX[QX]QX^QX_QX`QXbQXdQXfQXgQXhQXtQXcQXeQX~OTYOaQX~P!aOcZO~PVOe]O~PVOa_OTQX~P!aOS`OTcOWcOYcOZbO[aO^cO_cObQOdROfcOgcO~O`fO~P$bOUhO~OciO~PVOejO~PVOSkOTlOUlOWlOXlOYlOZlO[lO]lO^lO_lO`TObQOdROflOglOhlO~OaoO~P%tOTYO~Oa_OSjXTjXWjXYjXZjX[jX^jX_jX`jXbjXdjXfjXgjX~Oa_O~O`qO~P$bOTrOWrOXrOYrOZrO[rO]rO^rO_rO`rOarObrOcrOdrOerOfrOgrO~OhuO~P(cOTYOSnXUnXWnXXnXYnXZnX[nX]nX^nX_nX`nXanXbnXdnXfnXgnXhnX~OawO~P%tOhyO~P(cO`aWXYZ[T_vgZ~",
  goto: "#}tPPu}PPP!_PPPPPPPPPPPPPPPPP!c!o}}!s#P#T#]#k#q#w]WOQRX[^[VOQRX[^ScTeTl_nTsht[VOQRX[^Tl_nTdTe[VOQRX[^TcTeTm_n]VOQRX[^QXOQ[QQ^RVgX[^QthRxtQeTRpeQn_Rvn",
  nodeNames:
    "⚠ Prompt Item ExtensionCall Dollar Identifier LParen ExtensionItem String UnterminatedString Tag InvalidNumber Number Equals Comma Escaped DoublePipe DoubleColon LBrace RBrace LBracket RBracket Pipe Text RParen Randomizer RandomizerContent Strengthening Weakening NumericEmphasis NumericContent CloseAll",
  maxTerm: 38,
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData:
    "8e~R!SOX$_XZ%iZ]&^]^%i^p$_pq%iqr$_rs(ost$_tu)xux$_xy)}yz*Sz|$_|}*X}!O*^!O!Q$_!Q![0q![!]5[!]!_$_!_!`5i!`!b$_!c!}5n!}#O7T#O#P7Y#P#Q7w#Q#T$_#T#o5n#o#p7|#p#q8R#q#r8`#r#y$_#y#z&^#z$f$_$f$g&^$g#BY$_#BY#BZ&^#BZ$IS$_$IS$I_&^$I_$I|$_$I|$JO&^$JO$JT$_$JT$JU&^$JU$KV$_$KV$KW&^$KW&FU$_&FU&FV&^&FV;'S$_;'S;=`%c<%lO$_~$d_g~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}![$_!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~%fP;=`<%l$_~%nYv~X^%ipq%i#y#z%i$f$g%i#BY#BZ%i$IS$I_%i$I|$JO%i$JT$JU%i$KV$KW%i&FU&FV%i~&erv~g~OX$_XZ%iZ]&^]^%i^p$_pq%iqr$_st$_ux$_z|$_}![$_!]!_$_!`!b$_!c!}$_#Q#o$_#r#y$_#y#z&^#z$f$_$f$g&^$g#BY$_#BY#BZ&^#BZ$IS$_$IS$I_&^$I_$I|$_$I|$JO&^$JO$JT$_$JT$JU&^$JU$KV$_$KV$KW&^$KW&FU$_&FU&FV&^&FV;'S$_;'S;=`%c<%lO$_~(tVX~Or(ors)Zs#O(o#O#P)`#P;'S(o;'S;=`)r<%lO(o~)`OW~~)cTOY(oZ](o^;'S(o;'S;=`)r<%lO(o~)uP;=`<%l(o~)}OS~~*SOU~~*XOh~~*^O^~~*c`g~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!Q$_!Q![+e!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~+lb[~g~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O$_!O!P,t!P!Q$_!Q![+e!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~,ybg~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O$_!O!P.R!P!Q$_!Q![/b!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~.YbZ~g~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O$_!O!P.R!P!Q$_!Q![.R!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~/ib[~g~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O$_!O!P.R!P!Q$_!Q![/b!]!_$_!`!b$_!c!}$_#Q#o$_#r;'S$_;'S;=`%c<%lO$_~0xe[~g~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O2Z!O!P,t!P!Q$_!Q![3p!]!_$_!`!b$_!c!}2Z#Q#R$_#R#S2Z#S#T$_#T#o2Z#r;'S$_;'S;=`%c<%lO$_~2bdY~g~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O2Z!O!Q$_!Q![2Z!]!_$_!`!b$_!c!}2Z#Q#R$_#R#S2Z#S#T$_#T#o2Z#r;'S$_;'S;=`%c<%lO$_~3yeY~[~g~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O2Z!O!P,t!P!Q$_!Q![3p!]!_$_!`!b$_!c!}2Z#Q#R$_#R#S2Z#S#T$_#T#o2Z#r;'S$_;'S;=`%c<%lO$_~5aPg~![!]5d~5iOa~~5nO]~~5udT~g~OX$_Z]$_^p$_qr$_st$_ux$_z|$_}!O5n!O!Q$_!Q![5n!]!_$_!`!b$_!c!}5n#Q#R$_#R#S5n#S#T$_#T#o5n#r;'S$_;'S;=`%c<%lO$_~7YOd~~7]TOY7lZ]7l^;'S7l;'S;=`7q<%lO7l~7qO_~~7tP;=`<%l7l~7|Oe~~8ROb~~8WPf~#p#q8Z~8`O`~~8eOc~",
  tokenizers: [0],
  topRules: { Prompt: [0, 1] },
  tokenPrec: 471,
});
