[package]
name = "atelier-generation"
version = "0.1.0"
edition = "2024"
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
atelier-resource-catalog = { workspace = true }
futures-core = { workspace = true }
novelai-bridge = { workspace = true }
thiserror = { workspace = true }
