[package]
name = "atelier-prompt-resources"
version = "0.1.0"
edition = "2024"
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
atelier-prompt = { workspace = true }
atelier-generation = { workspace = true }
atelier-resource-catalog = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
futures-executor = { workspace = true }
